### ISSUE TITLE
SocketServer Issue

### ISSUE THREAD

**Issue by FabioEnne** [vdutor/TF-rex#1]
Hi, I'm trying to run your example but when I start it it throws me an error:

Cannot find module name socketserver, I've tryied to run it bth from Python2 and 3..

**Comment by vdutor** [comment]
Hi,
Thank you for your interest :)
The project currently only supports python3.
The `serversocket` package comes by default with the python3 installation.
Can you give me some more information about your system?

**Comment by FabioEnne** [comment]
yep, thanks for the quick answer I managed to make it work.. just a quick quetion, I trained the model to the 134 epoch...now I'm trying to make it play with the trained model.. is this the right command?

`python main.py play --modeldir logs` ?

Thanks

**Comment by vdutor** [comment]
You will have to run
`python main.py --training False --checkpoint_name logs/rex.ckpt`.
Or something similar depending on how you named the file and directory.

Also note that there is support for tensorboards :)
Running the command `tensorboard --logdir logs/` does the trick normally.

**Comment by FabioEnne** [comment]
ok...I'm a bit confused...sorry about that.. can you write down your workflow from beginning to end? 
Eg.
1) Start with training with this command.
2) learn from the trained model with this command.
3) play with the learned model with this command.

thanks for that :)

**Comment by vdutor** [comment]
1) You typically open your browser and surf to `127.0.0.1`.

2) Then, open 2 terminals. In the first, you run the command `python main.py --path ./logs/` and in the second you run the tensorboard `tensorboard --logdir logs/`.

3) Go back to your browser and refresh the page (Ctrl-F5). The browser will now connect to the python code and the T-rex will start to move.

4) Once your model is trained (this takes a while) you can use it by running `python main.py --training False --checkpoint_name ./logs/rex.ckpt `.

Hope this will get you started. Note that the code is definitely not finished and bugs may (read: will) be present :). However, I was already able to successfully train a couple of models. I will release them shortly.

**Comment by FabioEnne** [comment]
Ah ok, I asked because after trained it to 800th generation when I lunch `ython main.py --training False --checkpoint_name ./logs/rex.ckpt` it keep on crushing at the first cacti is it normal?  ;)

**Comment by FabioEnne** [comment]
do I have to run `python main.py --training ` between the first and the second step? because if I launch directly `ython main.py --path ./logs/` it tell me `trained model not found`

**Comment by vdutor** [comment]
Yes, it is. Sorry for the confusion, but in order to test the code I implemented a model which tries to crash as fast as possible. You can see this by inspecting the reward function in `get_state` in the `game_agent.py` file. If you want different behavior, you probably want to change the reward function used.

**Comment by FabioEnne** [comment]
alright cool, btw is it normale that after I trained to the 800th epoch, when I run it against the trained model it keep on crushing at the first cactus?

**Comment by vdutor** [comment]
Hi,
I added a trained model to the repo, it is easily able to achieve a score of around 700.
Just run `python main.py --notraining --logdir trained-model`.
