### ISSUE TITLE
How to start training from a checkpoint?

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [vdutor/TF-rex#4]
Hey, How can i train my T-rex from my last trained checkpoint? 
When i run 
`python3 main.py --training --logdir ./logs/ --checkpoint_nr 1600`
it says:
`PATH FOR STORING RESULTS ALREADY EXISTS - Results would be overwritten.`
but nothing would be happen.

**Comment by vdutor** [comment]
Please reopen this issue if still have problems

**Comment by alirezaafzalaghaei** [comment]
I'm looking for some way to keep on training from my last checkpoint.In other words i want increase the accuracy of my trained model without starting from scratch. Actually after running  `python3 main.py --training --logdir ./logs/ --checkpoint_nr 1600` script would be finish without any training!

**Comment by vdutor** [comment]
At the moment the code doesn't support this, but it is definitely possible to add this.

**Comment by alirezaafzalaghaei** [comment]
I'm noob in tensorflow, please add this feature to `TF-rex` in future updates :)

**Comment by vdutor** [comment]
I'll add it to my todo-list. Thanks for pointing it out :)
